### ISSUE TITLE
Incompatible with 2.9+

### ISSUE THREAD

**Issue by UnariVR** [p2or/blender-shapekey-extras#8] opened 2023-02-07 03:08 UTC
![image](https://user-images.githubusercontent.com/64662984/217138323-a08daf22-85ad-44a6-a033-4ba8fc28fb03.png)

**Comment by p2or** [comment] 2023-02-07 08:20
Hi @UnariVR,

thanks for your report. Just tried to install the [latest version of the add-on](https://github.com/p2or/blender-shapekey-extras/releases/tag/0.2.0) on **Blender 2.93 LTS** and I can not reproduce your issue. No errors during the installation and the add-on seems to work as expected. Are you using an older version of the add-on? 

<img width="591" alt="Screenshot 2023-02-07 at 09 17 31" src="https://user-images.githubusercontent.com/512368/217189637-63cfda97-669d-48ea-9c79-43dcb73ec019.png">

Cheers,
Christian

**Comment by UnariVR** [comment] 2023-02-07 12:48
> Hi @UnariVR,
> 
> thanks for your report. Just tried to install the [latest version of the add-on](https://github.com/p2or/blender-shapekey-extras/releases/tag/0.2.0) on **Blender 2.93 LTS** and I can not reproduce your issue. No errors during the installation and the add-on seems to work as expected. Are you using an older version of the add-on?
> 
> <img alt="Screenshot 2023-02-07 at 09 17 31" width="591" src="https://user-images.githubusercontent.com/512368/217189637-63cfda97-669d-48ea-9c79-43dcb73ec019.png">
> 
> Cheers, Christian

I found out why it wasn't working. I'm using another addon called Shapekeys+ and it seem the two are not compatible~ 
Sorry for the false post... >.<

**Comment by p2or** [comment] 2023-02-07 14:13
Ez. Yeah, looks like Shapekey+ removes the original shapekey panel and replaces that by a custom one (hence the "no panel" error), in genral a bad idea IMHO. Since there is not much I can do, closing for now. Cheers

**Closed as completed by p2or** 2023-02-07 14:13 UTC
